#!/bin/bash

# Vercel Environment Variables Setup Script
# Run this to get the commands to set up your Vercel environment

echo "======================================"
echo "🚀 Vercel Environment Variables Setup"
echo "======================================"
echo ""
echo "Run these commands in your terminal:"
echo ""
echo "# 1. Install Vercel CLI (if not already installed)"
echo "npm i -g vercel"
echo ""
echo "# 2. Login to Vercel"
echo "vercel login"
echo ""
echo "# 3. Link this project to Vercel"
echo "vercel link"
echo ""
echo "# 4. Generate a secure NEXTAUTH_SECRET"
echo "NEXTAUTH_SECRET=\$(openssl rand -base64 32)"
echo "echo \"Generated NEXTAUTH_SECRET: \$NEXTAUTH_SECRET\""
echo ""
echo "# 5. Set environment variables (replace with your actual values)"
echo "# DATABASE_URL - Get from Vercel Postgres, Neon, or Supabase"
echo "vercel env add DATABASE_URL production"
echo "# Paste: postgresql://user:password@host:5432/database"
echo ""
echo "vercel env add NEXTAUTH_URL production"
echo "# Paste: https://your-app.vercel.app"
echo ""
echo "vercel env add NEXTAUTH_SECRET production"
echo "# Paste the generated secret from step 4"
echo ""
echo "vercel env add GOOGLE_CLIENT_ID production"
echo "# Paste your Google OAuth Client ID from Google Cloud Console"
echo ""
echo "vercel env add GOOGLE_CLIENT_SECRET production"
echo "# Paste your Google OAuth Client Secret from Google Cloud Console"
echo ""
echo "vercel env add GOOGLE_PLACES_API_KEY production"
echo "# Paste your Google Places API Key (optional - for images/coordinates)"
echo ""
echo "# 6. (Optional) Set for Preview and Development environments too"
echo "# Repeat steps above with 'preview' and 'development' instead of 'production'"
echo ""
echo "# 7. Redeploy"
echo "vercel --prod"
echo ""
echo "======================================"
echo "✅ Setup Complete!"
echo "======================================"
echo ""
echo "📝 Next Steps:"
echo "1. Create a PostgreSQL database (Vercel Postgres recommended)"
echo "2. Run: npx prisma db push"
echo "3. (Optional) Seed database: npx prisma db seed"
echo "4. Update Google OAuth redirect URIs to include your Vercel URL"
echo ""
echo "📖 Full guide: See VERCEL_DEPLOYMENT_GUIDE.md"
